{
 "title": "Operator",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "energy_usg", "legendFormat": "__auto" },
    { "expr": "energy_req", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Earnings details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "money_charging", "legendFormat": "__auto" },
    { "expr": "money_operator", "legendFormat": "__auto" },
    { "expr": "money_parked", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total earnings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "total_money{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Parked cars",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "topk by() (5, cars_nr)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total energy capacity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "total_e_capacity", "legendFormat": "__auto" }
   ]
  }
 ]
}